### ISSUE TITLE
Shopware 6.2.1 breaks recovery/install/index.php installation

### ISSUE THREAD

**Issue by vdloo** [shopware/shopware#1030]
We've noticed that with the new [v6.2.1](https://github.com/shopware/platform/releases/tag/v6.2.1) the `php recovery/install/index.php` installation throws an error. My guess is that this is related to "[NEXT-6735](https://issues.shopware.com/issues/NEXT-6735) - It is now possible to set the default country during the installation" https://www.shopware.com/en/changelog/#6-2-1, but I haven't looked closely at it.

before on 6.2.0:
```
app@yqc1km-hypernode-magweb-aws:~/shopware/public$ php recovery/install/index.php --no-interaction --quiet --no-skip-import --db-host=localhost --db-user=app --db-password=secret --db-name=shopware_preinstall --shop-locale=en-GB --shop-host=vdloo.hypernode.io --shop-path= --shop-name='Demo shop' --shop-email='admin email' --shop-currency=EUR --admin-username=vdloo_admin --admin-password=secret --admin-email='admin email' --admin-firstname=admin --admin-lastname=admin --admin-locale=en-GB
app@yqc1km-hypernode-magweb-aws:~/shopware/public$ echo $?
0
```

now on 6.2.1:
```
app@yqc1km-hypernode-magweb-aws:~/shopware/public$ php recovery/install/index.php --no-interaction --quiet --no-skip-import --db-host=localhost --db-user=app --db-password=secret --db-name=shopware_preinstall --shop-locale=en-GB --shop-host=vdloo.hypernode.io --shop-path= --shop-name='Demo shop' --shop-email='admin email' --shop-currency=EUR --admin-username=vdloo_admin --admin-password=secret --admin-email='admin email' --admin-firstname=admin --admin-lastname=admin --admin-locale=en-GB
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Shopware\Recovery\Install\Service\ShopService::getCountryId() must be of the type string, null given, called in /data/web/shopware/vendor/shopware/recovery/Install/src/Service/ShopService.php on line 253 and defined in /data/web/shopware/vendor/shopware/recovery/Install/src/Service/ShopService.php:444
Stack trace:
#0 /data/web/shopware/vendor/shopware/recovery/Install/src/Service/ShopService.php(253): Shopware\Recovery\Install\Service\ShopService->getCountryId(NULL)
#1 /data/web/shopware/vendor/shopware/recovery/Install/src/Service/ShopService.php(40): Shopware\Recovery\Install\Service\ShopService->createSalesChannel(Object(Shopware\Recovery\Install\Struct\Shop))
#2 /data/web/shopware/vendor/shopware/recovery/Install/src/Command/InstallCommand.php(129): Shopware\Recovery\Install\Service\ShopService->updateShop(Object(Shopware\Recovery\Install\Struct\Shop))
#3 /data/web/shopware/vendor/shopware/recovery/Common/vendor/symfony/console/Command/Command.php(255): Shopware\Re in /data/web/shopware/vendor/shopware/recovery/Install/src/Service/ShopService.php on line 444

Fatal error: Uncaught TypeError: Argument 1 passed to Shopware\Recovery\Install\Service\ShopService::getCountryId() must be of the type string, null given, called in /data/web/shopware/vendor/shopware/recovery/Install/src/Service/ShopService.php on line 253 and defined in /data/web/shopware/vendor/shopware/recovery/Install/src/Service/ShopService.php:444
Stack trace:
#0 /data/web/shopware/vendor/shopware/recovery/Install/src/Service/ShopService.php(253): Shopware\Recovery\Install\Service\ShopService->getCountryId(NULL)
#1 /data/web/shopware/vendor/shopware/recovery/Install/src/Service/ShopService.php(40): Shopware\Recovery\Install\Service\ShopService->createSalesChannel(Object(Shopware\Recovery\Install\Struct\Shop))
#2 /data/web/shopware/vendor/shopware/recovery/Install/src/Command/InstallCommand.php(129): Shopware\Recovery\Install\Service\ShopService->updateShop(Object(Shopware\Recovery\Install\Struct\Shop))
#3 /data/web/shopware/vendor/shopware/recovery/Common/vendor/symfony/console/Command/Command.php(255): Shopware\Re in /data/web/shopware/vendor/shopware/recovery/Install/src/Service/ShopService.php on line 444
```

from the help menu or the interactive prompt I could not deduct a new flag that should be passed in order to set this Country ID:
```
app@yqc1km-hypernode-magweb-aws:~/shopware/public$ php recovery/install/index.php --help
Description:
  Installs and does the initial configuration of Shopware
Usage:
  install [options]
Options:
      --db-host=DB-HOST                  Database host [default: "localhost"]
      --db-port=DB-PORT                  Database port [default: "3306"]
      --db-socket=DB-SOCKET              Database socket
      --db-user=DB-USER                  Database user
      --db-password=DB-PASSWORD          Database password
      --db-name=DB-NAME                  Database name
      --no-skip-import                   Import database data even if a valid schema already exists
      --shop-locale=SHOP-LOCALE          Shop locale
      --shop-host=SHOP-HOST              Shop host [default: "localhost"]
      --shop-path=SHOP-PATH              Shop path
      --shop-name=SHOP-NAME              Shop name [default: "Demo shop"]
      --shop-email=SHOP-EMAIL            Shop email address [default: "your.email@shop.com"]
      --shop-currency=SHOP-CURRENCY      Shop currency
      --skip-admin-creation              If provided, no admin user will be created.
      --admin-username=ADMIN-USERNAME    Administrator username
      --admin-password=ADMIN-PASSWORD    Administrator password
      --admin-email=ADMIN-EMAIL          Administrator email address
      --admin-locale=ADMIN-LOCALE        Administrator locale
      --admin-firstname=ADMIN-FIRSTNAME  Administrator firstname
      --admin-lastname=ADMIN-LASTNAME    Administrator lastname
  -h, --help                             Display this help message
  -q, --quiet                            Do not output any message
  -V, --version                          Display this application version
      --ansi                             Force ANSI output
      --no-ansi                          Disable ANSI output
  -n, --no-interaction                   Do not ask any interactive question
  -e, --env=ENV                          The Environment name. [default: "production"]
  -v|vv|vvv, --verbose                   Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
```

**Comment by macster84** [comment]
Unfortunately still broken in 6.2.2. This "just" requires to add another parameter to the CLI. 
Are there any plans on fixing this in one of the next minor releases?

**Comment by shyim** [comment]
Has been fixed on master https://github.com/shopware/platform/commit/0c9959e9600a57c91bb4c28788295498ad199aea

**Comment by vdloo** [comment]
thanks!

**Comment by vdloo** [comment]
![shop_002](https://user-images.githubusercontent.com/1437341/89433046-1f3b1300-d742-11ea-92a4-2ec8fff7c734.png)

@shyim I've noticed this is still [not fixed in 6.3.0.1](https://github.com/shopware/platform/tree/v6.3.0.1/src/Recovery/Install). Do you know when this fix will be in an official release?

**Comment by shyim** [comment]
In the next regular update. 6.3.0.1 was an hot fix for 6.3.0.0

**Comment by vdloo** [comment]
alright, thanks for the quick reply!
