### ISSUE TITLE
npm build: Failed at the administration@1.0.0 build script.

### ISSUE THREAD

**Issue by NiklasTeich** [shopware/shopware#48]
- MAMP PRO 5.3
- OSX 10.11.6
- PHP 7.2.14
- node v12.3.1
- NPM 6.9.0
- Xcode 8.2.1

Install step 24/28 is not possible, execution aborted, a subcommand failed:
![install build failed](https://i.imgur.com/o8M2JCb.jpg)

**Comment by shyim** [comment]
You need to do bin/console administration:dump:bundles before 🤔

**Comment by NiklasTeich** [comment]
The `bin/console administration:dump:bundles` gives me a OK message (running it right before the installation), but the installation itself still fails ..

**Comment by Blur-Creative** [comment]
a --unsafe-perm at npm clean-istall should fix it.
add it to the .sh script at the dev-ops dir.

https://github.com/shopware/development/blob/master/dev-ops/administration/actions/install-dependencies.sh

change to

`npm clean-install --unsafe-perm --prefix vendor/shopware/platform/src/Administration/Resources/administration/`

https://github.com/shopware/development/blob/master/dev-ops/storefront/actions/install-dependencies.sh

change to

`npm --unsafe-perm --prefix vendor/shopware/platform/src/Storefront/Resources/ clean-install`

then do the install again.  
solved it for me

**Comment by NiklasTeich** [comment]
Thanks for your ideas! It's better, but still crashes. Now, a missing `Storefront.css` instead of the `Storefront.js` throws an error ..

![install css build failed](https://i.imgur.com/Qu41XDr.jpg)

**Comment by PaddyS** [comment]
Hey @NiklasTeich,

can you try this with Node Version 11?
You can use the [Node version manager](https://github.com/tj/n) for this, quite easy to use.

**Comment by NiklasTeich** [comment]
Hey @PaddyS!

I also tried the installation with downgraded versions of Node 11.9 und NPM 6.5, sadly without any further success ... :cry:

**Comment by PaddyS** [comment]
Hey @NiklasTeich,

we've had an equal issue a few minutes ago.
In this case, executing the following command fixed it:
`npm rebuild node-sass`

Can you try this and see if that fixes your issue?

**Comment by LighthouseIVM** [comment]
Hello, 

we still have this issue and we tried everything that was mentioned here.... still not working. 
Any other ideas ?

**Comment by janbuecker** [comment]
@klarstil will keep an eye on this issue. :)

**Comment by LighthouseIVM** [comment]
Any updates yet ?

**Comment by klarstil** [comment]
Hey @LighthouseIVM 

I took a quick look on the issue and it seems like a timing issue in our `copy-after-build` webpack plugin which causes the problem. I wasn't able to take a closer look on the issue yet and keep you updated when I have further information.

Best regards

**Comment by klarstil** [comment]
@LighthouseIVM I'm having a hard time to reproduce the issue on my local machine but I think I found the issue in the code related to the behavior described in this thread.

Would it be possible to test the following code and give us the results if the fix is working. Replace the content of the file `platform/src/Administration/Resources/common/webpack-copy-after-build/index.js`with the following: https://gist.github.com/klarstil/1d329cb5ec3f341804b878d46ea25207

The issue was the usage of the read and write streams of Node.js. The previous stream wasn't ended before we tried to write a new file.

Any feedback is welcome here.

**Comment by moehrenzahn** [comment]
Hi @klarstil, I just had this very issue when attempting a local installation on macOS, and replacing  `platform/src/Administration/Resources/common/webpack-copy-after-build/index.js` with the content from your gist resolved my issue!

**Comment by klarstil** [comment]
@moehrenzahn Awesome, thanks for your feedback. @LighthouseIVM provided me with the same feedback, so I created a PR in our internal systems with the change. It'll be in the repo soon :)

**Comment by klarstil** [comment]
We merged the changes on an internal feature branch which will be available shortly on here. Thanks for all the feedback and input. It's much appreciate.

I'll close the issue now.
